### PR TITLE
Fix linux wheel

### LINKED ISSUE #65: Linux wheel isn't on PyPI
Need to check this https://github.com/DBraun/DawDreamer/blob/e4be8670e570e6b5fb187e1c9f50fdf584d32030/.github/workflows/all.yml#L99-L117

### PR DESCRIPTION
**Pull request by meisenzahl**
Fixes #65

### CODE REVIEW

**Comment by meisenzahl** [comment]
@DBraun I would like to help with this. Can you give me a hint what exactly the error message was?

**Comment by DBraun** [comment]
Can you see the error logs with your GitHub account? https://github.com/DBraun/DawDreamer/runs/5468392330?check_suite_focus=true

**Comment by meisenzahl** [comment]
Yes, I can see the error logs.

I am puzzled by this error message:

```
thirdparty/faust/architecture/android/app/lib/libsndfile/lib/armeabi-v7a/libsndfile.so
These files might be built against the wrong OS, causing problems with
    thirdparty/faust/architecture/android/app/lib/libsndfile/lib/arm64-v8a/libsndfile.so
auditwheel.
```
Apparently the built library is checked in for Android: https://github.com/grame-cncm/faust/tree/0c6d52d9c20f839481a5c35f9547aa26c778e2c1/architecture/android/app/lib/libsndfile/lib/armeabi-v7a

I'll try what happens if I delete the file.

**Review by DBraun — APPROVED** [review]

**Comment by DBraun** [comment]
0.6.4 now has some Linux wheels and they work in Google Colab!

```python
!python --version
!pip install dawdreamer
import dawdreamer as daw
engine = daw.RenderEngine(44100, 512)

faustp = engine.make_faust_processor("faust")
faustp.set_dsp_string("process = os.osc(440) <: _, _;")
faustp.compile()
engine.load_graph([(faustp, [])])

engine.render(10.)
audio = engine.get_audio()
print(audio)
```

**Pull request closed without merging**
